#!/bin/bash -x
#==============================================================================#
#                                mtasa-install                                 #
#------------------------------------------------------------------------------#
#  This shellscript installs MTA:SA on your server. You can configure it and   #
#  modify it as desired, you can even improve it if you want.                  #
#==============================================================================#

echo -e "SCRIPT INSTALL \033[01;32mMTA SERVER LINUX\033[01;37m!"
echo Adquira sua VPS em: nicehosting.com.br/vps.html

apt update && apt upgrade -y
apt install unzip -y


ARCH_TYPE=""

getArchitecture()
{
    if ((1<<32)); then
        ARCH_TYPE="_x64"
    fi
}

downloadFiles()
{
    wget https://linux.mtasa.com/dl/multitheftauto_linux${ARCH_TYPE}.tar.gz
    wget https://linux.mtasa.com/dl/baseconfig.tar.gz
}

unpack()
{
    tar -xf multitheftauto_linux${ARCH_TYPE}.tar.gz
    tar -xf baseconfig.tar.gz
}

moveConfig()
{
    mv baseconfig/* multitheftauto_linux${ARCH_TYPE}/mods/deathmatch
    rm -rf baseconfig
    cd multitheftauto_linux${ARCH_TYPE}
}

installResources()
{
    mkdir mods/deathmatch/resources
    cd mods/deathmatch/resources
    wget https://mirror.mtasa.com/mtasa/resources/mtasa-resources-latest.zip
    unzip mtasa-resources-latest.zip
    cd ../../..
}

clean()
{
    rm -f ../multitheftauto_linux${ARCH_TYPE}.tar.gz
    rm -f ../baseconfig.tar.gz
    rm -f mods/deathmatch/resources/mtasa-resources-latest.zip
}

main()
{
    getArchitecture
    clean
    downloadFiles
    unpack
    moveConfig
    installResources
    clean

    if ((1<<32)); then # 64 bits
        echo "Instalação pronta! Digite ./mta-server64 para ligar o servidor"
    else
        echo "Instalação pronta! Digite ./mta-server para ligar o servidor"
    fi
}

main # calling program entry point

echo "INSTALANDO BIBLIOTECAS NECESSARIAS..."

apt-get install libreadline5 -y
apt-get install libncursesw5 -y
apt-get install lib32ncursesw5 -y
sudo ln -s /usr/lib/libtinfo.so.6 /usr/lib/libtinfo.so.5

echo "TUDO JÁ FOI INSTALADO E O SEU SERVIDOR ESTÁ PRONTO PARA O USO !"
